FROM python:3.7

WORKDIR /Users/kazi/github/automation-projects/RestAPIAutomationFW
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . /Users/kazi/github/automation-projects/RestAPIAutomationFW